import type { Metadata } from 'next'
import './globals.css'
import { BrowserConsoleProvider } from '@/components/browser-console-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <BrowserConsoleProvider>
          {children}
        </BrowserConsoleProvider>
      </body>
    </html>
  )
}
